#!/bin/sh

# Provides:          nix-daemon
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Start nix-daemon

DAEMON=/nix/var/nix/profiles/default/bin/nix-daemon
PIDFILE=/var/run/nix-daemon.pid

case "$1" in
  start)
    echo "Starting nix-daemon..."
    start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON
    ;;
  stop)
    echo "Stopping nix-daemon..."
    start-stop-daemon --stop --pidfile $PIDFILE
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0
