[symlinks]
"config/fish/config.fish" = "/home/mees/.config/fish/config.fish"
"config/fish/fish_variables" = "/home/mees/.config/fish/fish_variables"
"config/fish/functions/fish_mode_prompt.fish" = "/home/mees/.config/fish/functions/fish_mode_prompt.fish"
"config/fish/functions/fish_prompt.fish" = "/home/mees/.config/fish/functions/fish_prompt.fish"
"config/fish/functions/fish_right_prompt.fish" = "/home/mees/.config/fish/functions/fish_right_prompt.fish"
"config/fish/functions/prompt_segment.fish" = "/home/mees/.config/fish/functions/prompt_segment.fish"
"config/fuzzel/fuzzel.ini" = "/home/mees/.config/fuzzel/fuzzel.ini"
"config/ghostty/config" = "/home/mees/.config/ghostty/config"
"config/hypr/hypridle.conf" = "/home/mees/.config/hypr/hypridle.conf"
"config/hypr/hyprlock.conf" = "/home/mees/.config/hypr/hyprlock.conf"
"config/ignis/config.py" = "/home/mees/.config/ignis/config.py"
"config/ignis/icons/NixOS.png" = "/home/mees/.config/ignis/icons/NixOS.png"
"config/ignis/icons/battery-charging.svg" = "/home/mees/.config/ignis/icons/battery-charging.svg"
"config/ignis/icons/battery-empty.svg" = "/home/mees/.config/ignis/icons/battery-empty.svg"
"config/ignis/icons/battery-full.svg" = "/home/mees/.config/ignis/icons/battery-full.svg"
"config/ignis/icons/battery25.svg" = "/home/mees/.config/ignis/icons/battery25.svg"
"config/ignis/icons/battery50.svg" = "/home/mees/.config/ignis/icons/battery50.svg"
"config/ignis/icons/battery75.svg" = "/home/mees/.config/ignis/icons/battery75.svg"
"config/ignis/icons/bluetooth.svg" = "/home/mees/.config/ignis/icons/bluetooth.svg"
"config/ignis/icons/brightness.svg" = "/home/mees/.config/ignis/icons/brightness.svg"
"config/ignis/icons/chrome-symbolic.svg" = "/home/mees/.config/ignis/icons/chrome-symbolic.svg"
"config/ignis/icons/empty.svg" = "/home/mees/.config/ignis/icons/empty.svg"
"config/ignis/icons/firefox-browser-symbolic.svg" = "/home/mees/.config/ignis/icons/firefox-browser-symbolic.svg"
"config/ignis/icons/lock-square.svg" = "/home/mees/.config/ignis/icons/lock-square.svg"
"config/ignis/icons/log-out.svg" = "/home/mees/.config/ignis/icons/log-out.svg"
"config/ignis/icons/media-art-fallback.png" = "/home/mees/.config/ignis/icons/media-art-fallback.png"
"config/ignis/icons/music.svg" = "/home/mees/.config/ignis/icons/music.svg"
"config/ignis/icons/network.svg" = "/home/mees/.config/ignis/icons/network.svg"
"config/ignis/icons/pause.svg" = "/home/mees/.config/ignis/icons/pause.svg"
"config/ignis/icons/play.svg" = "/home/mees/.config/ignis/icons/play.svg"
"config/ignis/icons/skip-next.svg" = "/home/mees/.config/ignis/icons/skip-next.svg"
"config/ignis/icons/skip-prev.svg" = "/home/mees/.config/ignis/icons/skip-prev.svg"
"config/ignis/icons/sound-high.svg" = "/home/mees/.config/ignis/icons/sound-high.svg"
"config/ignis/icons/spotify-symbolic.svg" = "/home/mees/.config/ignis/icons/spotify-symbolic.svg"
"config/ignis/icons/system-restart.svg" = "/home/mees/.config/ignis/icons/system-restart.svg"
"config/ignis/icons/system-shut.svg" = "/home/mees/.config/ignis/icons/system-shut.svg"
"config/ignis/icons/wifi-off.svg" = "/home/mees/.config/ignis/icons/wifi-off.svg"
"config/ignis/icons/wifi-warning.svg" = "/home/mees/.config/ignis/icons/wifi-warning.svg"
"config/ignis/icons/wifi.svg" = "/home/mees/.config/ignis/icons/wifi.svg"
"config/ignis/icons/wireguard.svg" = "/home/mees/.config/ignis/icons/wireguard.svg"
"config/ignis/src/__init__.py" = "/home/mees/.config/ignis/src/__init__.py"
"config/ignis/src/bar.py" = "/home/mees/.config/ignis/src/bar.py"
"config/ignis/src/calendarWindow.py" = "/home/mees/.config/ignis/src/calendarWindow.py"
"config/ignis/src/controlCenter.py" = "/home/mees/.config/ignis/src/controlCenter.py"
"config/ignis/style.scss" = "/home/mees/.config/ignis/style.scss"
"config/mako/config" = "/home/mees/.config/mako/config"
"config/niri/config.kdl" = "/home/mees/.config/niri/config.kdl"
"config/niri/cut" = "/home/mees/.config/niri/cut"
"config/niri/scripts/close.sh" = "/home/mees/.config/niri/scripts/close.sh"
"config/nvim/init.lua" = "/home/mees/.config/nvim/init.lua"
"config/nvim/lazy-lock.json" = "/home/mees/.config/nvim/lazy-lock.json"
"config/nvim/lua/config/autocomplete.lua" = "/home/mees/.config/nvim/lua/config/autocomplete.lua"
"config/nvim/lua/config/lazy.lua" = "/home/mees/.config/nvim/lua/config/lazy.lua"
"config/nvim/lua/config/lsp-diagnostics.lua" = "/home/mees/.config/nvim/lua/config/lsp-diagnostics.lua"
"config/nvim/lua/config/lsp.lua" = "/home/mees/.config/nvim/lua/config/lsp.lua"
"config/nvim/lua/config/settings.lua" = "/home/mees/.config/nvim/lua/config/settings.lua"
"config/nvim/lua/config/statusline.lua" = "/home/mees/.config/nvim/lua/config/statusline.lua"
"config/nvim/lua/plugins/autocomplete.lua" = "/home/mees/.config/nvim/lua/plugins/autocomplete.lua"
"config/nvim/lua/plugins/fuzzy.lua" = "/home/mees/.config/nvim/lua/plugins/fuzzy.lua"
"config/nvim/lua/plugins/lsp-diagnostics.lua" = "/home/mees/.config/nvim/lua/plugins/lsp-diagnostics.lua"
"config/nvim/lua/plugins/md.lua" = "/home/mees/.config/nvim/lua/plugins/md.lua"
"config/nvim/lua/plugins/statusline.lua" = "/home/mees/.config/nvim/lua/plugins/statusline.lua"
"config/scripts/install-cursor.sh" = "/home/mees/.config/scripts/install-cursor.sh"
"config/scripts/wireguard-walker.sh" = "/home/mees/.config/scripts/wireguard-walker.sh"
"config/walker/config.toml" = "/home/mees/.config/walker/config.toml"
"config/wpaperd/config.toml" = "/home/mees/.config/wpaperd/config.toml"
"git/gitconfig" = "/home/mees/.gitconfig"
"theme/cursor_theme/default/index.theme" = "/home/mees/.local/share/icons/default/index.theme"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/bullet-symbolic.svg" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/bullet-symbolic.svg"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/bullet-symbolic.symbolic.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/bullet-symbolic.symbolic.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/bullet@2-symbolic.symbolic.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/bullet@2-symbolic.symbolic.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/check-symbolic.svg" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/check-symbolic.svg"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/check-symbolic.symbolic.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/check-symbolic.symbolic.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/check@2-symbolic.symbolic.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/check@2-symbolic.symbolic.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/dash-symbolic.svg" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/dash-symbolic.svg"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/dash-symbolic.symbolic.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/dash-symbolic.symbolic.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/dash@2-symbolic.symbolic.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/dash@2-symbolic.symbolic.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/devel-symbolic.svg" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/devel-symbolic.svg"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-dark.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-dark.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-dark@2.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-dark@2.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-disabled-dark.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-disabled-dark.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-disabled-dark@2.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-disabled-dark@2.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-disabled.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-disabled.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-disabled@2.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-above-disabled@2.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-above.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-above.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-above@2.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-above@2.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-dark.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-dark.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-dark@2.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-dark@2.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-disabled-dark.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-disabled-dark.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-disabled-dark@2.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-disabled-dark@2.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-disabled.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-disabled.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-disabled@2.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-below-disabled@2.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-below.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-below.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-below@2.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-horz-scale-has-marks-below@2.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-dark.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-dark.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-dark@2.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-dark@2.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-disabled-dark.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-disabled-dark.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-disabled-dark@2.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-disabled-dark@2.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-disabled.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-disabled.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-disabled@2.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-above-disabled@2.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-above.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-above.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-above@2.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-above@2.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-dark.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-dark.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-dark@2.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-dark@2.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-disabled-dark.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-disabled-dark.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-disabled-dark@2.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-disabled-dark@2.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-disabled.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-disabled.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-disabled@2.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-below-disabled@2.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-below.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-below.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-below@2.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/slider-vert-scale-has-marks-below@2.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/text-select-end-dark.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/text-select-end-dark.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/text-select-end-dark@2.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/text-select-end-dark@2.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/text-select-end.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/text-select-end.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/text-select-end@2.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/text-select-end@2.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/text-select-start-dark.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/text-select-start-dark.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/text-select-start-dark@2.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/text-select-start-dark@2.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/text-select-start.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/text-select-start.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/assets/text-select-start@2.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/assets/text-select-start@2.png"
"theme/gtk/adw-gtk3-dark/gtk-3.0/gtk-dark.css" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/gtk-dark.css"
"theme/gtk/adw-gtk3-dark/gtk-3.0/gtk.css" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/gtk.css"
"theme/gtk/adw-gtk3-dark/gtk-3.0/thumbnail.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-3.0/thumbnail.png"
"theme/gtk/adw-gtk3-dark/gtk-4.0/assets/bullet-symbolic.svg" = "/home/mees/.themes/adw-gtk3-dark/gtk-4.0/assets/bullet-symbolic.svg"
"theme/gtk/adw-gtk3-dark/gtk-4.0/assets/bullet-symbolic.symbolic.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-4.0/assets/bullet-symbolic.symbolic.png"
"theme/gtk/adw-gtk3-dark/gtk-4.0/assets/bullet@2-symbolic.symbolic.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-4.0/assets/bullet@2-symbolic.symbolic.png"
"theme/gtk/adw-gtk3-dark/gtk-4.0/assets/check-symbolic.svg" = "/home/mees/.themes/adw-gtk3-dark/gtk-4.0/assets/check-symbolic.svg"
"theme/gtk/adw-gtk3-dark/gtk-4.0/assets/check-symbolic.symbolic.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-4.0/assets/check-symbolic.symbolic.png"
"theme/gtk/adw-gtk3-dark/gtk-4.0/assets/check@2-symbolic.symbolic.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-4.0/assets/check@2-symbolic.symbolic.png"
"theme/gtk/adw-gtk3-dark/gtk-4.0/assets/dash-symbolic.svg" = "/home/mees/.themes/adw-gtk3-dark/gtk-4.0/assets/dash-symbolic.svg"
"theme/gtk/adw-gtk3-dark/gtk-4.0/assets/dash-symbolic.symbolic.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-4.0/assets/dash-symbolic.symbolic.png"
"theme/gtk/adw-gtk3-dark/gtk-4.0/assets/dash@2-symbolic.symbolic.png" = "/home/mees/.themes/adw-gtk3-dark/gtk-4.0/assets/dash@2-symbolic.symbolic.png"
"theme/gtk/adw-gtk3-dark/gtk-4.0/assets/devel-symbolic.svg" = "/home/mees/.themes/adw-gtk3-dark/gtk-4.0/assets/devel-symbolic.svg"
"theme/gtk/adw-gtk3-dark/gtk-4.0/gtk-dark.css" = "/home/mees/.themes/adw-gtk3-dark/gtk-4.0/gtk-dark.css"
"theme/gtk/adw-gtk3-dark/gtk-4.0/gtk.css" = "/home/mees/.themes/adw-gtk3-dark/gtk-4.0/gtk.css"
"theme/gtk/adw-gtk3-dark/gtk-4.0/libadwaita-tweaks.css" = "/home/mees/.themes/adw-gtk3-dark/gtk-4.0/libadwaita-tweaks.css"
"theme/gtk/adw-gtk3-dark/gtk-4.0/libadwaita.css" = "/home/mees/.themes/adw-gtk3-dark/gtk-4.0/libadwaita.css"
"theme/gtk/adw-gtk3-dark/index.theme" = "/home/mees/.themes/adw-gtk3-dark/index.theme"
"theme/gtk/gtk3-settings.ini" = "/home/mees/.config/gtk-3.0/settings.ini"
"theme/gtk/gtk4-dark.css" = "/home/mees/.config/gtk-4.0/gtk.css"

[templates]
