[symlinks]
"fish/config.fish" = "/home/mees/.config/fish/config.fish"
"fish/fish_variables" = "/home/mees/.config/fish/fish_variables"
"fish/functions/fish_mode_prompt.fish" = "/home/mees/.config/fish/functions/fish_mode_prompt.fish"
"fish/functions/fish_prompt.fish" = "/home/mees/.config/fish/functions/fish_prompt.fish"
"fish/functions/fish_right_prompt.fish" = "/home/mees/.config/fish/functions/fish_right_prompt.fish"
"fish/functions/prompt_segment.fish" = "/home/mees/.config/fish/functions/prompt_segment.fish"
"fontconfig/conf.d/nix-fonts.conf" = "/home/mees/.config/fontconfig/conf.d/nix-fonts.conf"
"fontconfig/fonts.conf" = "/home/mees/.config/fontconfig/fonts.conf"
"git/gitconfig" = "/home/mees/.gitconfig"
"nvim/init.lua" = "/home/mees/.config/nvim/init.lua"
"nvim/lazy-lock.json" = "/home/mees/.config/nvim/lazy-lock.json"
"nvim/lua/config/autocomplete.lua" = "/home/mees/.config/nvim/lua/config/autocomplete.lua"
"nvim/lua/config/lazy.lua" = "/home/mees/.config/nvim/lua/config/lazy.lua"
"nvim/lua/config/lsp-diagnostics.lua" = "/home/mees/.config/nvim/lua/config/lsp-diagnostics.lua"
"nvim/lua/config/lsp.lua" = "/home/mees/.config/nvim/lua/config/lsp.lua"
"nvim/lua/config/settings.lua" = "/home/mees/.config/nvim/lua/config/settings.lua"
"nvim/lua/config/statusline.lua" = "/home/mees/.config/nvim/lua/config/statusline.lua"
"nvim/lua/plugins/autocomplete.lua" = "/home/mees/.config/nvim/lua/plugins/autocomplete.lua"
"nvim/lua/plugins/fuzzy.lua" = "/home/mees/.config/nvim/lua/plugins/fuzzy.lua"
"nvim/lua/plugins/lsp-diagnostics.lua" = "/home/mees/.config/nvim/lua/plugins/lsp-diagnostics.lua"
"nvim/lua/plugins/statusline.lua" = "/home/mees/.config/nvim/lua/plugins/statusline.lua"
"packages/cli-packages.nix" = "/home/mees/.config/packages/cli-packages.nix"
"packages/lsp.nix" = "/home/mees/.config/packages/lsp.nix"
"packages/ui-packages.nix" = "/home/mees/.config/packages/ui-packages.nix"

[templates]
